### ISSUE TITLE
EGPSRの不具合

### ISSUE THREAD

**Issue by t-inamura** [RoboCupatHomeSim/RoboCupatHomeSim#1]
srandにtaskNumを引数として渡した場合，5回目の試行が終了した後に物体の再配置が行われずそこで競技が止まってしまう（プログラムはエラー等で落ちることなく動いたままだった）

**Comment by HideyukiWada** [comment]
living roomに設置されている3つの机のうち1つの机にのみ物体を配置可能な設定から，
3つの机全てに物体を配置可能な設定に変更した所解決しました．
