### ISSUE TITLE
Refereeサービスの不具合

### ISSUE THREAD

**Issue by t-inamura** [RoboCupatHomeSim/RoboCupatHomeSim#2]
moderatorがをブロードキャストしたGo to the ○○, grasp the ×× and come back here.というメッセージをRefereeサービスが受信した場合，Refereeサービスがエラーを吐く

**Comment by t-inamura** [comment]
上記の問題はEGPSRで観測されているとの報告が和田君からあり

**Comment by HideyukiWada** [comment]
Windows.NET版のSIGService.cpp内の処理に問題があったため起きていた不具合だったようです．
具体的には，Socket通信で受け取ったデータのヘッダー部とメッセージ部の区切り文字として使われている , がメッセージ部に含まれていた場合に対応できていなかったことが原因のようです．
SIGServiceに
https://github.com/SIGVerse/SIGService/commit/c55c42679d480fc24910404713330c644ab3e300
の修正を行い，ビルドしたSIGService.dllをRefereeサービスで使用するようにしたところRefereeサービスがエラーを吐かなくなりました．
