### ISSUE TITLE
FollowMe における不具合

### ISSUE THREAD

**Issue by t-inamura** [RoboCupatHomeSim/RoboCupatHomeSim#3]
taskNumが13,14の時に最後のチェックポイントをOperatorが通過直後，Operatorが腰まで地面に埋まる問題が起きた
どちらもnode6.txtを使用するのでこのファイルが原因の可能性あり？

**Comment by HideyukiWada** [comment]
RoboCupatHomeSim/RoboCupatHomeSim/blob/master/FollowMe/RoboCup/Template/Operator.cppの318行目と336行目
my->setPosition(pos.x()+addx, HEIGHT[i], pos.z()+addz);
のHEIGHTの添字をjからiに修正する事で解決しました．

iは追跡対象者の経路が格納されたファイルの行数を表す変数，
jは追跡対象者の歩行モーションが格納されたファイルの行数を表す変数であり，
これらの添字が入れ替わっていたため最終チェックポイント通過後に不適切な座標でsetPositionされていたようです．
